### ISSUE TITLE
Fix hanging state with broken image and no broker updates

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/playlist-label#25]
- [x] Fix peewee database lock error #36
- [x] Fix tap response bug #38
- [x] Fix bug where taps aren't collected #39
- [x] Investigate why the label stops getting updated from the broker
- ~[ ] Investigate why the images break, possibly related to above~ We don't have images anymore

**Notes**:
* You can only have one consumer of a media player at a time (playlist labels acknowledge messages as they consume them)
